# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Trey Moore
tagline:          A Blog
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Trey Moore
  url:            https://twitter.com/dtmooreiv
  email:          dtmooreiv@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dtmooreiv/blog
