# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Trey Moore
tagline:          A Blog
description:	  A description
url:              http://treymoore.me
paginate:         1
baseurl:          http://dtmooreiv.github.io/blog/
author:
  name:           Trey Moore
  url:            https://twitter.com/dtmooreiv
  email:          dtmooreiv@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dtmooreiv/blog
