name: Trey Moore
markdown: redcarpet
highlighter: pygments
permalink: /:title
description: Blog of Software Developer Trey Moore.
defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "default"
